<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup>
  <!-- Evita que el proyecto principal compile los archivos del proyecto de tests -->
  <Compile Remove="ProyectoPII.Tests\**\*.cs" />
  <EmbeddedResource Remove="ProyectoPII.Tests\**\*" />
  <None Remove="ProyectoPII.Tests\**\*" />
</ItemGroup>

</Project>